const LANE_WIDTH = 15

module.exports = {
  LANE_WIDTH: LANE_WIDTH,
  DEST_THRESHOLD: 0.05,
  GRID_SIZE: LANE_WIDTH,
  MAX_WAYPOINTS: 20,
  MAX_SPEED: 0.5,
  DEFAULT_VEHICLE_INTERVAL: 500,
  CAR_WIDTH: 10,
  CAR_LENGTH: 20
}